# Generated by Django 6.0.8 on 2026-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0003_auto_20210419_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxvm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
